// Package nonce provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package nonce

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Address defines model for Address.
type Address = string

// NonceResponse defines model for NonceResponse.
type NonceResponse struct {
	Address *Address `json:"address,omitempty"`
	ChainId *uint64  `json:"chainId,omitempty"`
	Nonce   *uint64  `json:"nonce,omitempty"`
}

// XNonceAuthHash defines model for XNonceAuthHash.
type XNonceAuthHash = string

// XNonceAuthSignature defines model for XNonceAuthSignature.
type XNonceAuthSignature = string

// XNonceAuthSigner defines model for XNonceAuthSigner.
type XNonceAuthSigner = Address

// GetNonceParams defines parameters for GetNonce.
type GetNonceParams struct {
	XNONCEAUTHHASH      XNonceAuthHash      `json:"X-NONCE-AUTH-HASH"`
	XNONCEAUTHSIGNATURE XNonceAuthSignature `json:"X-NONCE-AUTH-SIGNATURE"`
	XNONCEAUTHSIGNER    XNonceAuthSigner    `json:"X-NONCE-AUTH-SIGNER"`
}

// ReturnNonceParams defines parameters for ReturnNonce.
type ReturnNonceParams struct {
	XNONCEAUTHHASH      XNonceAuthHash      `json:"X-NONCE-AUTH-HASH"`
	XNONCEAUTHSIGNATURE XNonceAuthSignature `json:"X-NONCE-AUTH-SIGNATURE"`
	XNONCEAUTHSIGNER    XNonceAuthSigner    `json:"X-NONCE-AUTH-SIGNER"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetNonce request
	GetNonce(ctx context.Context, chainId uint64, address Address, params *GetNonceParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SyncNonce request
	SyncNonce(ctx context.Context, chainId uint64, address Address, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReturnNonce request
	ReturnNonce(ctx context.Context, chainId uint64, address Address, nonce uint64, params *ReturnNonceParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetNonce(ctx context.Context, chainId uint64, address Address, params *GetNonceParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetNonceRequest(c.Server, chainId, address, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SyncNonce(ctx context.Context, chainId uint64, address Address, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSyncNonceRequest(c.Server, chainId, address)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReturnNonce(ctx context.Context, chainId uint64, address Address, nonce uint64, params *ReturnNonceParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReturnNonceRequest(c.Server, chainId, address, nonce, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetNonceRequest generates requests for GetNonce
func NewGetNonceRequest(server string, chainId uint64, address Address, params *GetNonceParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "chainId", runtime.ParamLocationPath, chainId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "address", runtime.ParamLocationPath, address)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/nonce/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	var headerParam0 string

	headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-NONCE-AUTH-HASH", runtime.ParamLocationHeader, params.XNONCEAUTHHASH)
	if err != nil {
		return nil, err
	}

	req.Header.Set("X-NONCE-AUTH-HASH", headerParam0)

	var headerParam1 string

	headerParam1, err = runtime.StyleParamWithLocation("simple", false, "X-NONCE-AUTH-SIGNATURE", runtime.ParamLocationHeader, params.XNONCEAUTHSIGNATURE)
	if err != nil {
		return nil, err
	}

	req.Header.Set("X-NONCE-AUTH-SIGNATURE", headerParam1)

	var headerParam2 string

	headerParam2, err = runtime.StyleParamWithLocation("simple", false, "X-NONCE-AUTH-SIGNER", runtime.ParamLocationHeader, params.XNONCEAUTHSIGNER)
	if err != nil {
		return nil, err
	}

	req.Header.Set("X-NONCE-AUTH-SIGNER", headerParam2)

	return req, nil
}

// NewSyncNonceRequest generates requests for SyncNonce
func NewSyncNonceRequest(server string, chainId uint64, address Address) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "chainId", runtime.ParamLocationPath, chainId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "address", runtime.ParamLocationPath, address)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/nonce/%s/%s/sync", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewReturnNonceRequest generates requests for ReturnNonce
func NewReturnNonceRequest(server string, chainId uint64, address Address, nonce uint64, params *ReturnNonceParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "chainId", runtime.ParamLocationPath, chainId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "address", runtime.ParamLocationPath, address)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "nonce", runtime.ParamLocationPath, nonce)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/nonce/%s/%s/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	var headerParam0 string

	headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-NONCE-AUTH-HASH", runtime.ParamLocationHeader, params.XNONCEAUTHHASH)
	if err != nil {
		return nil, err
	}

	req.Header.Set("X-NONCE-AUTH-HASH", headerParam0)

	var headerParam1 string

	headerParam1, err = runtime.StyleParamWithLocation("simple", false, "X-NONCE-AUTH-SIGNATURE", runtime.ParamLocationHeader, params.XNONCEAUTHSIGNATURE)
	if err != nil {
		return nil, err
	}

	req.Header.Set("X-NONCE-AUTH-SIGNATURE", headerParam1)

	var headerParam2 string

	headerParam2, err = runtime.StyleParamWithLocation("simple", false, "X-NONCE-AUTH-SIGNER", runtime.ParamLocationHeader, params.XNONCEAUTHSIGNER)
	if err != nil {
		return nil, err
	}

	req.Header.Set("X-NONCE-AUTH-SIGNER", headerParam2)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetNonce request
	GetNonceWithResponse(ctx context.Context, chainId uint64, address Address, params *GetNonceParams, reqEditors ...RequestEditorFn) (*GetNonceResponse, error)

	// SyncNonce request
	SyncNonceWithResponse(ctx context.Context, chainId uint64, address Address, reqEditors ...RequestEditorFn) (*SyncNonceResponse, error)

	// ReturnNonce request
	ReturnNonceWithResponse(ctx context.Context, chainId uint64, address Address, nonce uint64, params *ReturnNonceParams, reqEditors ...RequestEditorFn) (*ReturnNonceResponse, error)
}

type GetNonceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NonceResponse
}

// Status returns HTTPResponse.Status
func (r GetNonceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetNonceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SyncNonceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r SyncNonceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SyncNonceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ReturnNonceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r ReturnNonceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReturnNonceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetNonceWithResponse request returning *GetNonceResponse
func (c *ClientWithResponses) GetNonceWithResponse(ctx context.Context, chainId uint64, address Address, params *GetNonceParams, reqEditors ...RequestEditorFn) (*GetNonceResponse, error) {
	rsp, err := c.GetNonce(ctx, chainId, address, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetNonceResponse(rsp)
}

// SyncNonceWithResponse request returning *SyncNonceResponse
func (c *ClientWithResponses) SyncNonceWithResponse(ctx context.Context, chainId uint64, address Address, reqEditors ...RequestEditorFn) (*SyncNonceResponse, error) {
	rsp, err := c.SyncNonce(ctx, chainId, address, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSyncNonceResponse(rsp)
}

// ReturnNonceWithResponse request returning *ReturnNonceResponse
func (c *ClientWithResponses) ReturnNonceWithResponse(ctx context.Context, chainId uint64, address Address, nonce uint64, params *ReturnNonceParams, reqEditors ...RequestEditorFn) (*ReturnNonceResponse, error) {
	rsp, err := c.ReturnNonce(ctx, chainId, address, nonce, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReturnNonceResponse(rsp)
}

// ParseGetNonceResponse parses an HTTP response from a GetNonceWithResponse call
func ParseGetNonceResponse(rsp *http.Response) (*GetNonceResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetNonceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NonceResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseSyncNonceResponse parses an HTTP response from a SyncNonceWithResponse call
func ParseSyncNonceResponse(rsp *http.Response) (*SyncNonceResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SyncNonceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseReturnNonceResponse parses an HTTP response from a ReturnNonceWithResponse call
func ParseReturnNonceResponse(rsp *http.Response) (*ReturnNonceResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReturnNonceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieves the next available nonce
	// (POST /nonce/{chainId}/{address})
	GetNonce(ctx echo.Context, chainId uint64, address Address, params GetNonceParams) error
	// Synchronize nonce with blockchain
	// (POST /nonce/{chainId}/{address}/sync)
	SyncNonce(ctx echo.Context, chainId uint64, address Address) error
	// Returns unused nonce
	// (PUT /nonce/{chainId}/{address}/{nonce})
	ReturnNonce(ctx echo.Context, chainId uint64, address Address, nonce uint64, params ReturnNonceParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetNonce converts echo context to params.
func (w *ServerInterfaceWrapper) GetNonce(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "chainId" -------------
	var chainId uint64

	err = runtime.BindStyledParameterWithLocation("simple", false, "chainId", runtime.ParamLocationPath, ctx.Param("chainId"), &chainId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter chainId: %s", err))
	}

	// ------------- Path parameter "address" -------------
	var address Address

	err = runtime.BindStyledParameterWithLocation("simple", false, "address", runtime.ParamLocationPath, ctx.Param("address"), &address)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter address: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNonceParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-NONCE-AUTH-HASH" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-NONCE-AUTH-HASH")]; found {
		var XNONCEAUTHHASH XNonceAuthHash
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-NONCE-AUTH-HASH, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-NONCE-AUTH-HASH", runtime.ParamLocationHeader, valueList[0], &XNONCEAUTHHASH)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-NONCE-AUTH-HASH: %s", err))
		}

		params.XNONCEAUTHHASH = XNONCEAUTHHASH
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-NONCE-AUTH-HASH is required, but not found"))
	}
	// ------------- Required header parameter "X-NONCE-AUTH-SIGNATURE" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-NONCE-AUTH-SIGNATURE")]; found {
		var XNONCEAUTHSIGNATURE XNonceAuthSignature
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-NONCE-AUTH-SIGNATURE, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-NONCE-AUTH-SIGNATURE", runtime.ParamLocationHeader, valueList[0], &XNONCEAUTHSIGNATURE)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-NONCE-AUTH-SIGNATURE: %s", err))
		}

		params.XNONCEAUTHSIGNATURE = XNONCEAUTHSIGNATURE
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-NONCE-AUTH-SIGNATURE is required, but not found"))
	}
	// ------------- Required header parameter "X-NONCE-AUTH-SIGNER" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-NONCE-AUTH-SIGNER")]; found {
		var XNONCEAUTHSIGNER XNonceAuthSigner
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-NONCE-AUTH-SIGNER, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-NONCE-AUTH-SIGNER", runtime.ParamLocationHeader, valueList[0], &XNONCEAUTHSIGNER)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-NONCE-AUTH-SIGNER: %s", err))
		}

		params.XNONCEAUTHSIGNER = XNONCEAUTHSIGNER
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-NONCE-AUTH-SIGNER is required, but not found"))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetNonce(ctx, chainId, address, params)
	return err
}

// SyncNonce converts echo context to params.
func (w *ServerInterfaceWrapper) SyncNonce(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "chainId" -------------
	var chainId uint64

	err = runtime.BindStyledParameterWithLocation("simple", false, "chainId", runtime.ParamLocationPath, ctx.Param("chainId"), &chainId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter chainId: %s", err))
	}

	// ------------- Path parameter "address" -------------
	var address Address

	err = runtime.BindStyledParameterWithLocation("simple", false, "address", runtime.ParamLocationPath, ctx.Param("address"), &address)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter address: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SyncNonce(ctx, chainId, address)
	return err
}

// ReturnNonce converts echo context to params.
func (w *ServerInterfaceWrapper) ReturnNonce(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "chainId" -------------
	var chainId uint64

	err = runtime.BindStyledParameterWithLocation("simple", false, "chainId", runtime.ParamLocationPath, ctx.Param("chainId"), &chainId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter chainId: %s", err))
	}

	// ------------- Path parameter "address" -------------
	var address Address

	err = runtime.BindStyledParameterWithLocation("simple", false, "address", runtime.ParamLocationPath, ctx.Param("address"), &address)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter address: %s", err))
	}

	// ------------- Path parameter "nonce" -------------
	var nonce uint64

	err = runtime.BindStyledParameterWithLocation("simple", false, "nonce", runtime.ParamLocationPath, ctx.Param("nonce"), &nonce)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter nonce: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ReturnNonceParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-NONCE-AUTH-HASH" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-NONCE-AUTH-HASH")]; found {
		var XNONCEAUTHHASH XNonceAuthHash
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-NONCE-AUTH-HASH, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-NONCE-AUTH-HASH", runtime.ParamLocationHeader, valueList[0], &XNONCEAUTHHASH)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-NONCE-AUTH-HASH: %s", err))
		}

		params.XNONCEAUTHHASH = XNONCEAUTHHASH
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-NONCE-AUTH-HASH is required, but not found"))
	}
	// ------------- Required header parameter "X-NONCE-AUTH-SIGNATURE" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-NONCE-AUTH-SIGNATURE")]; found {
		var XNONCEAUTHSIGNATURE XNonceAuthSignature
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-NONCE-AUTH-SIGNATURE, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-NONCE-AUTH-SIGNATURE", runtime.ParamLocationHeader, valueList[0], &XNONCEAUTHSIGNATURE)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-NONCE-AUTH-SIGNATURE: %s", err))
		}

		params.XNONCEAUTHSIGNATURE = XNONCEAUTHSIGNATURE
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-NONCE-AUTH-SIGNATURE is required, but not found"))
	}
	// ------------- Required header parameter "X-NONCE-AUTH-SIGNER" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-NONCE-AUTH-SIGNER")]; found {
		var XNONCEAUTHSIGNER XNonceAuthSigner
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-NONCE-AUTH-SIGNER, got %d", n))
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-NONCE-AUTH-SIGNER", runtime.ParamLocationHeader, valueList[0], &XNONCEAUTHSIGNER)
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-NONCE-AUTH-SIGNER: %s", err))
		}

		params.XNONCEAUTHSIGNER = XNONCEAUTHSIGNER
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-NONCE-AUTH-SIGNER is required, but not found"))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ReturnNonce(ctx, chainId, address, nonce, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/nonce/:chainId/:address", wrapper.GetNonce)
	router.POST(baseURL+"/nonce/:chainId/:address/sync", wrapper.SyncNonce)
	router.PUT(baseURL+"/nonce/:chainId/:address/:nonce", wrapper.ReturnNonce)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RUUY7bNhC9CjHNp2xpvc4uoq86iZMNim4KO2kDBFtgTI0tJhKpkpTWrqDD9AA9RS5W",
	"kJKjeGMnWuRv+2dT5Myb9968GrjKCyVJWgNxDQVqzMmS9v/eXSvJaVba9ApN6k6EhBhSwoQ0BCAxJ4jh",
	"3ej69fWz+Wj29s3V6Gq2vIIANP1VCk0JxFaXFIDhKeXoSthd4R4Zq4XcQNMEX7RZio1EW2oa1mv56uX1",
	"7M3bxfyHGpIe3m2++GarR5rWEMNPYc9q2H414SxJNBkDjUPQHbo3+/O4BtpiXmSucbR9OpmeP548Pn92",
	"efaCzyaXq/n0bBJdzJ9OLp+cz6dTOnu+vlhdPIcACrSWtMP/Z7R9j6P1bPQiGj25qadR8wiCuwQE4Mdf",
	"kCmUNJ7qQquCtBXkYWCPaNBAAfAUhXyVuBdrpXO0EEMppL2Y9u2FtLQh7a5L13/Y5ebzkVp9IG5b+oRc",
	"K/eeK2mRW89djiKDGCrkGVbjAqtMyJ837nTMVd5r+vunf9wN9htW2ad/pcOTkOFaFFYoR+LcpqSpzNkf",
	"mGVkmWeL/YoSN6QZZpm6NWytNLMa+UchN8zPY5hVDCslEsZVlgkjlDRuImG9pAdlIICKtGkbRuNofOZw",
	"qIIkFgJiOB9H40krbeqFCH2PsO6YbsK6U6nx+injSTgcZEFWC6ocspSYpK1lWKHIcJVRi5mhTFhZJGi7",
	"S59Hcgw7bVwlD0z7305jeEnWD+Px9Xnxvlsih7mne2+mH1+b4Gj9vfW+VX+IzY6j6OcL74ThvV70uXbv",
	"Zw7djRuu3VZvhkkU7d1P0guPRZEJ7iUKPxinfj2Q38Ms8Nt16KLXv/gtNGWeo94NspUjGDfOEt2q37gK",
	"py0cmp3kp3283EmeaiXF32Q638oyX5Fmt8KmbJUp/tEX9XZWFelbLbyjh7jZVX9wdj7hmO8o+wXRHc93",
	"CL63sLX/1GZUeTyiSi0NK2VpKOmaWnUyi3zurkvtIpqVhr5Ssy34EOPpSPH9sv3vku/7CfWVq45Zt2n+",
	"CwAA//+JYBgRAAsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
